apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    control-plane: pipelines-multikueue-controller
    app.kubernetes.io/app: pipelines-multikueue-controller
spec:
  selector:
    matchLabels:
      control-plane: pipelines-multikueue-controller
      app.kubernetes.io/name: tekton-kueue
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller
      labels:
        control-plane: pipelines-multikueue-controller
        app.kubernetes.io/name: tekton-kueue
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /controller
        args:
          - controller
          - --leader-elect
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=:8443
        image: controller:latest
        imagePullPolicy: Always
        name: controller
        ports:
        - containerPort: 8443
          name: metrics-server
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: pipelines-multikueue-plugin-controller
      terminationGracePeriodSeconds: 10
